kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-for-apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web
  labels:
    app: apache-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-web
  template:
    metadata:
      labels:
        app: apache-web
    spec:
      volumes:
        - name: apache-web
          persistentVolumeClaim:
            claimName: storage-for-apache
      containers:
      - name: apache-web
        image: httpd
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs/
            name: apache-web
---
apiVersion: v1
kind: Service
metadata:
  name: apache-web
spec:
  selector:
    app: apache-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001